language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
      - libgtk2.0-0
      - libgconf-2-4
      - libasound2
      - libxtst6
      - libxss1
      - libnss3
      - xvfb
script:
  - yarn run lint
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: sources
